#!/bin/sh
### BEGIN INIT INFO
# Provides:          tmts
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop tmts server
### END INIT INFO

export JAVA_HOME=JAVA_HOME=/opt/java
export TMTS_HOME=/opt/tmts

case $1 in
    start)
        sh $TMTS_HOME/bin/start.sh
    ;;
    stop)
        sh $TMTS_HOME/bin/stop.sh
    ;;
    *)
    echo "Usage: service tmts {start|stop}"
    exit 1
    ;;
esac
exit 0